# Generated by Django 5.2 on 2025-04-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
